### ISSUE TITLE
Linux install issue. Need to use -std=c99 to compile

### ISSUE THREAD

**Issue by JohnSpeno** [Noirello/PyLDAP#3]
Hi,

Thanks for this module. On RedHat 6, I find that I need to use the -std=c99 compiler option otherwise I see this error doing when doing a 'pip install pyldap':

` building '_ldap' extension
    gcc -pthread -Werror=declaration-after-statement -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=2.4.20 -IModules -I/usr/include -I/usr/include/sasl -I/usr/local/include -I/usr/local/include/sasl -I/home/jspeno200/virtualenvs/dashboard/include -I/usr/local/include/python3.4m -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.4/Modules/LDAPObject.o
    In file included from Modules/LDAPObject.c:18:
    /usr/include/sasl/sasl.h:349: warning: function declaration isn’t a prototype
    Modules/LDAPObject.c: In function ‘l_ldap_result4’:
    Modules/LDAPObject.c:1023: error: ISO C90 forbids mixed declarations and code
    error: command 'gcc' failed with exit status 1
`

Is there something we can do to make installing work without needing the extra compiler flags? Please let me know how I can help.

**Comment by Noirello** [comment]
You're probably looking for another Python LDAP module: https://github.com/pyldap/pyldap/ 
I'm planning to rename my module in the feature to avoid these misunderstandings with that and also with the original python-ldap module. (Regardless that I've started to use this name earlier, but never published on PyPI).

**Comment by JohnSpeno** [comment]
I think you are correct. I'm sorry about that. And it is very nice to have options. Thanks.
